teamProject/app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .forms import LoginForm, SignupForm
from .models import User
from . import db
from flask_login import logout_user, login_required, login_user, current_user

from werkzeug.security import generate_password_hash, check_password_hash
# created auth for user authorization such login and sign up


auth = Blueprint('auth', __name__)

# our sign in page


@auth.route("/", methods=['GET', 'POST'])
@auth.route("/signin", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # if post method then we request items
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        remember = request.form.get('remember_me')
        # search for the user in the db
        user = User.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            login_user(user, remember=remember)
            flash('Success! welcome', category='success')
            # if user exist we redirect the user to their home page with their username
            return redirect(url_for('routes.home', username=user.get_username()))
        else:
            flash('invalid email or password!', category='error')
    return render_template("signin.html", form=form)

# to log out the user


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

# used to sign up users (create)


@auth.route("/signup", methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if request.method == 'POST' and form.validate_on_submit():
        email = request.form.get('email')
        username = request.form.get('username')

        email_check = User.query.filter_by(email=email).first()
        name_check = User.query.filter_by(username=username).first()
        # check if username or email already exists
        if email_check:
            flash('email already in use.', category='error')
            return render_template("signup.html", form=form)

        if name_check:
            flash('username already in use.', category='error')
            return render_template("signup.html", form=form)

        # if no error we create the user and save in the db
        password = request.form.get('password')

        hashed_password = generate_password_hash(
            password, method='sha512')
        user = User(email=email,
                    username=username, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Success! welcome', category='success')
        # redirect to login
        return redirect(url_for('auth.login'))

    return render_template("signup.html", form=form)

teamProject/app/routes.py
from flask import current_app, Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from .forms import SignupForm, UploadForm

import uuid as uuid
import config
import os


from .models import User, Post
from . import db

# this blueprint is for the remaining routes
views = Blueprint('routes', __name__)

# route to delete user


@views.route('/delete')
@login_required
def delete():

    # we utilize the current_user from flask login
    delete_user = User.query.filter_by(id=current_user.id).first()

    try:

        db.session.delete(delete_user)
        db.session.commit()
        flash('account deleted')
        return redirect(url_for('auth.login'))

    except:
        flash('failed to delete account')


@views.route('/home/<username>/post', methods=['GET', 'POST'])
@login_required
def post(username):
    form = UploadForm()  # from forms.py that enables file upload for pic post

    if request.method == 'POST' and form.validate_on_submit():  # checks with validators
        post = request.form.get('post')
        image_id = None
        image = request.files['image']
        if image:  # checks to see if the image is there after request from files
            try:
                # creates image id to store in database
                image_id = str(uuid.uuid1()) + "_" + \
                    secure_filename(image.filename)
                image.save(os.path.join(
                    current_app.config['UPLOAD_FOLDER'], image_id))
                new_post = Post(
                    data=post, user_id=current_user.id, image=image_id)
                db.session.add(new_post)
                db.session.commit()
                flash('Post uploaded', category='success')
                # Once added to db, it will redirect to the user home page
                return redirect(url_for('routes.home', username=username))

            except OSError as err:
                print("OS error:", err)
                flash('fail')

        if len(post) > 250:
            # ensures post length is no more than 250 characters
            flash('Text no more than 250 characters!', category='error')
        else:
            new_post = Post(data=post, user_id=current_user.id, image=image_id)
            db.session.add(new_post)
            db.session.commit()
            flash('Post uploaded', category='success')
            return redirect(url_for('routes.home', username=username))

    return render_template('post.html', user=current_user, username=username, form=form)


@views.route('/home/<username>/delete-post/<int:id>')
@login_required
# takes a an id so the deleted post can be identified and removed from the database
def deletePost(id, username):
    deleted_post = Post.query.get_or_404(id)
    db.session.delete(deleted_post)
    db.session.commit()

    return redirect(url_for('routes.home', username=username))


# logged in users home route
@views.route('/home/<username>/', methods=['GET', 'POST'])
@login_required
def home(username):
    user = User.query.filter_by(username=current_user.username).first()
    bio = user.get_bio()
    posts = user.get_posts()
    profile_pic = user.get_pic()

    # we pass a lot of things because the home page would have a basic logic to display another users homepage found in visiting
    return render_template('home.html', username=current_user.username, userhome=current_user.username, bio=bio, posts=posts, profile_pic=profile_pic, user=user)

# route for search


@views.route("/home/<username>/search", methods=['GET', 'POST'])
@login_required
def search(username):
    if request.method == 'POST':
        # the user will search for the username and we will use to query
        searched_username = request.form.get('searched')
        searched = User.query.filter_by(username=searched_username).first()

        # if the user exists we can redirect to that user home page
        if searched:
            # redirect to that users home page
            return redirect(url_for('routes.visiting', username=current_user.username, other_user=searched_username))
        else:

            flash('user does not exist.', category='error')

    return render_template('search.html', username=current_user.username)

# very similar to the home route but in this case we request and query based on the other users db


@views.route('/visiting/<username>/<other_user>', methods=['GET', 'POST'])
@login_required
def visiting(username, other_user):

    other_user = User.query.filter_by(username=other_user).first()
    current = User.query.filter_by(username=current_user.username).first()

    # the post is for users to follow each other updating the db in models
    if request.method == 'POST':
        follow(current, other_user)
        return redirect(url_for('routes.visiting', username=current_user.username, other_user=other_user.get_username()))
    other_username = other_user.get_username()
    bio = other_user.get_bio()
    posts = other_user.get_posts()
    profile_pic = other_user.get_pic()
    following = current.is_following(other_user)
    return render_template(
        'home.html', username=current_user.username, userhome=other_username, bio=bio, posts=posts, following=following, profile_pic=profile_pic, user=other_user)


def follow(current, other_user):

    # adding a button so people can follow each other
    if not current.is_following(other_user):
        # user toggle button and resulted in a following
        current_user.follow(other_user)   # if not, follow them
        db.session.commit()  # apply change to the db
        flash(f'followed ')

    else:
        current_user.unfollow(other_user)  # if already following
        db.session.commit()
        flash(f'Unfollowed')  # if apply change to db


# user to update the user information
@views.route('/update-info/<username>', methods=['GET', 'POST'])
@login_required
def update(username):
    form = SignupForm()
    update_user = User.query.filter_by(
        username=current_user.username).first()

    if request.method == 'POST':

        update_user.username = request.form.get('username')
        update_user.update_bio(request.form.get('bio'))
        if request.files['profile_pic']:
            # we have a special case for the profile pic since it would be a bit harder to keep safe than the username and bio
            # if the user submits a picture only then will we update it

            update_user.profile_pic = request.files['profile_pic']

            pic_filename = secure_filename(update_user.profile_pic.filename)
            # create a random name
            pic_name = str(uuid.uuid1()) + "_" + pic_filename
            # save pic at location in init

            # save profile_pic string
            update_user.profile_pic = pic_name

            save_file = request.files['profile_pic']
            try:

                db.session.commit()

                # os creates the string that we will save at the designated folder created in init (it is in static)
                save_file.save(os.path.join(
                    current_app.config['UPLOAD_FOLDER'], pic_name))

                flash('update changed')

                return redirect(url_for('routes.home', username=username))
            except OSError as err:
                print("OS error:", err)
                flash('fail')
                return render_template('update.html', username=username, form=form, update_user=update_user)
        db.session.commit()
        return redirect(url_for('routes.home', username=username))
    return render_template('update.html', username=username, form=form,  update_user=update_user, bio=update_user.get_bio())

teamProject/app/templates/base.html
<!DOCTYPE html>

<!--this is used for the login and sign up page template-->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />

    <title>{% block title %} Base {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="static/css/login.css" />
  </head>

  <body>
    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem">
              <div class="card-body p-5 text-center">
                <div class="mb-md-5 mt-md-4 pb-5">
                
                
                  
                  {% block content %} 
                  <!--start home page in home page create link for login and sign up-->
                  
                  
                {% endblock %}
                
                
              </div>
            </div>
          </div>
        </div>
      </div>
      
      
    </section>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

teamProject/app/templates/followers.html
<!-- <div class="jumbotron">
    <h2 style="text-align: center;">User list</h2>
    {% for user in users%}
          <a>{{user.username}}</a>
    {% endfor %}
  </div> -->




<!-- <div class="jumbotron">
  <h2 style="text-align: center;">These people are following you:</h2>
  {% for user in users%}
        <a href="{{url_for('routes.visiting',username=current_user.username, other_user=user.username)}}">{{user.username}}</a>
  {% endfor %}
</div> -->


<!-- <div class="list-group">
    <h2 style="text-align: center;">These users are following you:</h2>
    {% for user in users%}
          <a href="{{ url_for('routes.visiting',username=current_user.username, other_user=user.username)}}" class="list-group-item list-group-item-action">{{user.username}}</a>
    {% endfor %}
</div> -->

<div class="list-group">
    <h2 style="text-align: center;">These users are following you:</h2>
      {% for user in users%}
            <a href="{{ url_for('routes.visiting',username=current_user.username, other_user=user.username)}}" class="list-group-item list-group-item-action">{{user.username}}</a>
      {% endfor %}
    </div>

teamProject/app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='css/main.css') }}" />

  <title>{% block title %} {{userhome}}'s Home {% endblock %}</title>

</head>
<!--inserting new code -->


<!--inserting new code end-->

<body style="background-color: #eee;">
  
    <div class="container py-5">
      <div class="row">
        <div class="col">
          
          <nav class="navbar navbar-expand-lg bg-light rounded-3 p-3 mb-4">
            <a class="navbar-brand" href="#"></a>
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNavAltMarkup"
              aria-controls="navbarNavAltMarkup"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
        
                
                <a class="nav-item nav-link" href="{{url_for('routes.home', username=username)}}">Profile</a>
                
                <a class="nav-item nav-link" href="{{url_for('routes.post', username=username)}}">Post</a>
                
                <a class="nav-item nav-link" href="{{url_for('routes.search', username=username)}}">
                  Search
                </a>
                <!--dropdown-->
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    User Settings
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{url_for('routes.update', username=username)}}">Update Account</a></li>
                    <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Sign out</a></li>
                    
                    <li><a type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    Delete account
                    </a></li>
                    
                    
                    
        
                  </ul>
                </li>
                <!--end dropdown-->   
                  <!-- Modal -->
                  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="staticBackdropLabel">WARNING!</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <p>Are you sure you want to delete?</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CLOSE</button>
                          <a type="button" class="btn btn-danger" href="{{url_for('routes.delete')}}">DELETE</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!--end modal-->
        
              </div>  
          </nav>
        </div>
      </div>
  
      <!--end nav-->

  <!--Content-->
  {%block display%}
  <div class="col">
    <div class="card mb-4">
      <div class="card-body text-center">

        {% if profile_pic %}
        
          <img src="{{url_for('static', filename='images/' + profile_pic)}}" class="rounded mx-auto d-block" alt="" width="300">
        {% else %}
          <img src="{{url_for('static', filename='images/default_image.png')}}" alt="" width="200">        
        {% endif %}
        <h5 class="my-3">{{userhome}}</h5>
        {% if username != userhome %}
    
    
    <form method='POST' >
      {% if following %}      
              <button type="submit" class="btn btn-outline-primary active" autocomplete="off">Following</button>
      {% else %}
              <button type="submit" class="btn btn-outline-primary" autocomplete="off">Follow</button>  
      {% endif %}
    </form>
    {% endif %}
        <p class="text-muted mb-1">{{bio}}</p>
        <ul>
        
          <li> {{user.followers.count()}} followers </li>
          <li> {{user.followed.count()}} following </li>
          
        </ul>
        
        </div>
      </div>
    </div>


    <div class="col">
        <div class="card mb-4">
          <div class="card-body">
            {% for post in posts %}
                <li class="list-group-item ">
                  <div class="mb-5">
                    
                    <div style="text-align: left;">
                        {% if post.image %}
                    
                        <img src="{{url_for('static', filename='images/' + post.image)}}" width="200" height="200" class="rounded mx-auto d-block float-left">
                        {% endif%}
                        
                    </div>
                
                    <div style="text-align: left;">
                        {{ post.data }}
                    </div>

                    

                    {%if username == userhome %}
                    <div style="display: inline-block; position: absolute;
                    right: 0;">
                    <form action ='/home/{{username}}/' method="POST">
                        <a href="/home/{{username}}/delete-post/{{post.id}}" class="btn btn-outline-secondary btn-sm" style="display: inline">Delete</a>
                    </form>
                    {% endif%}



                {% endfor %}
            </ul>
            
            </div>
          </div>
        </div>  
    </div>

  
  {% endblock %}
  {% with messages = get_flashed_messages() %} {% if messages %}
            <ul class="flashes">
              {% for message in messages %}
              <li>{{ message }}</li>
              {% endfor %}
            </ul>
            {% endif %} {% endwith %} 



  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"
  ></script>
</body>

</html>

teamProject/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />

    <title>{% block title %} Base {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="#"
            >Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href='#'>search</a>
          <a class="nav-item nav-link" href='#'>post</a>
          <a class="nav-item nav-link" href={{url_for('auth.logout')}}>sign out</a>
          <a class="nav-item nav-link disabled" href='#'>delete</a>
        </ul>
          <form method= "POST" action"{{url_for('auth.search')}}" class="d-flex">
            {{form.hidden_tag()}}
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search",name="searched">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </div>
      </div>
    </nav>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

teamProject/app/templates/login.html
{% extends 'base.html' %}
{% block title %} Log In {% endblock %}
{% block content %} {{ form.hidden_tag() }}
<form method="POST" action="/">
    <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
    <p class="text-white-50 mb-5">
      Please enter your login and password
    </p>

    
    <div class="form-outline form-white mb-4">
        
        {{ form.email.label(class =
        "form-label", style = "float: left") }}
        {{ form.email(class = "form-control", size = 32, placeholder = "enter email")}}
    </div>

    <div class="form-outline form-white mb-4">
        
        {{ form.password.label(class =
        "form-label", style = "float: left") }}
        {{ form.password(class = "form-control", size = 32, placeholder = "enter password")}}
    </div>

    <br/>
    <p>{{ form.remember_me() }}
        {{form.remember_me.label}}
    </p>

    

    <p class="small mb-5 pb-lg-2">
      <a class="text-white-50" href="#!">Forgot password?</a>
    </p>

    <p>{{ form.submit(class="btn btn-outline-light btn-lg px-5") }}</p>
    
    
  </form>
</div>

<div>
  <p class="mb-0">
    Don't have an account?
    <a class="button" href="/signup">Sign Up</a>
  </p>
</div>
{% endblock %}

teamProject/app/templates/messages.html
{% extends "feed.html" %}

{% block app_content %}
    <h1>{{ _('Messages') }}</h1>
    {% for post in messages %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Newer messages') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Older messages') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

teamProject/app/templates/post.html
{% extends "home.html" %} {% block title %} Make a Post {% endblock %} {% block
    display %}
    <h1 align="center">Posts</h1>
    
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-light text-black-50" style="border-radius: 1rem">
            <div class="card-body p-5 text-center">
              <div class="mt-md-4 pb-5">
                <form
                    action="{{url_for('routes.post', username=username)}}"
                    enctype="multipart/form-data"
                    method="POST"
                >
                <form method="POST" enctype="multipart/form-data">
                    {{ form.csrf_token }}
                  <textarea
                    name="post"
                    id="post"
                    class="form-control"
                    rows="10"
                  ></textarea>
                  <br />
                  <div align="center">
                    <button type="submit" class="btn btn-outline-success">
                      Add Post
                    </button>
                  </div>
                  <div align="right">
                    {{current_user.image}} {{ form.image.label(class =
                    "form-label", style = "float: left") }} {{ form.image(class =
                    "form-control")}}
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    {%endblock%}
    

teamProject/app/templates/search.html
{% extends 'home.html' %} {% block title %} Search User {% endblock %} {%block
display%}

<div class="col">
  <div class="card mb-4">
    <div class="card-body">
      <form method="POST" action="">
        <h5>Please enter username</h5>
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="searched"
        />
        <div class="mb-md-5 mt-md-4">
          <button type="submit" class="btn btn-outline-success">search</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

teamProject/app/templates/send_message.html
{% extends "feed.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Send Message to %(recipient)s', recipient=recipient) }}</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

teamProject/app/templates/signin.html
{% extends 'base.html' %}
{% block title %} Sign In {% endblock %}
{% block content %} {{ form.hidden_tag() }}
<form method="POST" action="/">
    <h2 class="fw-bold mb-2 text-uppercase">Sign in</h2>
    <p class="text-white-50 mb-5">
      Please enter your login and password
    </p>

    
    <div class="form-outline form-white mb-4">
        
        {{ form.email.label(class =
        "form-label", style = "float: left") }}
        {{ form.email(class = "form-control", size = 32)}}
    </div>

    <div class="form-outline form-white mb-4">
        
        {{ form.password.label(class =
        "form-label", style = "float: left") }}
        {{ form.password(class = "form-control", size = 32)}}
    </div>

    {% with messages = get_flashed_messages() %}
                {% if messages %}
                <ul class=flashes>
                {% for message in messages %}
                  <li>{{ message }}</li>
                  {% endfor %}
            
                </ul>
                  {% endif %}
                  {% endwith %}

    <br/>
    <p>{{ form.remember_me() }}
        {{form.remember_me.label}}
    </p>

    

    <p>{{ form.submit(class="btn btn-outline-light btn-lg px-5") }}</p>
    
    
  </form>
</div>

<div>
  <p class="mb-0">
    Don't have an account?
    <a class="button" href="/signup">Sign Up</a>
  </p>
</div>

{% endblock %}

teamProject/app/templates/update.html
{% extends 'home.html' %} {% block title %} Update User Information{% endblock
%} {%block display%}

<div class="col">
  <div class="card mb-4">
    <div class="card-body">
      <form
        action="{{url_for('routes.update', username=username)}}"
        enctype="multipart/form-data"
        method="POST"
      >
        <h5>Update information</h5>
        <div class="mt-2 col-md-12">
          {{ form.profile_pic.label(class = "form-label", style = "float: left")
          }} {{ form.profile_pic(class = "form-control")}}
        </div>

        <!--Username-->
        <div class="mt-2 col-md-12">
          {{ form.username.label(class = "form-label", style = "float: left") }}
          {{ form.username(class = "form-control", value=update_user.username)}}
          must be 6 characters
        </div>

        <!--bio-->
        <div class="mt-2 col-md-12">
          <label for="bio"> About me </label>
          <textarea
            name="bio"
            id="bio"
            class="form-control"
            rows="10"
            cols="10"
          >
{{bio}}
          </textarea>
          max of 250 words
        </div>

        <div class="mt-2 col-md-12">
          <br />
          <input
            type="submit"
            class="btn btn-outline-secondary"
            value="Update Information"
          />
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}